blueprint:
  name: Sun Elevation Switch Control
  domain: automation
  description: This blueprint allows you to control a switch based on the sun's elevation, with adjustable offset degrees for turning it on and off. v2
  source_url: https://raw.githubusercontent.com/NH-Networks/homeassistant/main/Sun%20elevation%20trigger%20blueprint.yaml
  input:
    switch_entity:
      name: Switch Entity
      description: The switch entity to be controlled.
      selector:
        entity:
          domain: [light, switch, input_boolean]

    on_offset:
      name: On Offset (degrees)
      description: The offset in degrees for the sun's elevation to turn the switch on.
      default: 0
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider

    off_offset:
      name: Off Offset (degrees)
      description: The offset in degrees for the sun's elevation to turn the switch off.
      default: 0
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider

trigger:
  platform: numeric_state
  entity_id: sun.sun
  attribute: elevation

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state | float > trigger.from_state.state | float }}"
        sequence:
          - condition: numeric_state
            entity_id: sun.sun
            below: "{{ state_attr('sun.sun', 'elevation') + off_offset }}"
            for:
              minutes: 5
          - service: switch.turn_off
            target:
              entity_id: !input switch_entity
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state | float < trigger.from_state.state | float }}"
        sequence:
          - condition: numeric_state
            entity_id: sun.sun
            above: "{{ state_attr('sun.sun', 'elevation') + on_offset }}"
            for:
              minutes: 5
          - service: switch.turn_on
            target:
              entity_id: !input switch_entity
