blueprint:
  name: Time-based Entity Switch Off
  domain: automation
  input:
    entity:
      name: Entity
      description: The entity to be switched off.
      selector:
        entity:
    time_helper:
      name: Time Helper
      description: The time helper entity that determines the switch-off time.
      selector:
        entity:
          domain: input_datetime

trigger:
  platform: time
  at: input_datetime.time_helper

action:
  - service: homeassistant.turn_off
    target:
      entity_id: !input entity
